/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;

/**
 *
 * @author lam_m
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public static String username = "";
    public Admin(String user) {
        initComponents();
        username = user;
        usuario.setText(username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        label1 = new java.awt.Label();
        usuario = new java.awt.Label();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        Agregar = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        Busqueda = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        Respaldo = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");

        label1.setText("Bienvendio: ");

        usuario.setText("label2");

        jMenu4.setText("Cuenta");

        jMenuItem1.setText("Administrar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Usuarios");

        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        jMenu5.add(Agregar);

        jMenuItem4.setText("Dar baja");
        jMenu5.add(jMenuItem4);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Busqueda");

        Busqueda.setText("Busqueda");
        Busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedaActionPerformed(evt);
            }
        });
        jMenu6.add(Busqueda);

        jMenuBar1.add(jMenu6);

        jMenu8.setText("Respaldo");

        Respaldo.setText("Respaldo");
        Respaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RespaldoActionPerformed(evt);
            }
        });
        jMenu8.add(Respaldo);

        jMenuBar1.add(jMenu8);

        jMenu7.setText("Salir");

        jMenuItem6.setText("Salir");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem6);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(352, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(278, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void BusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Busqueda(username).setVisible(true);
        
    }//GEN-LAST:event_BusquedaActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
       
        Login l = new Login();
        l.setVisible(true);
       
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void RespaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RespaldoActionPerformed
        JFileChooser choose = new JFileChooser();         
       choose.setDialogTitle("Seleccione una carpeta de destino"); 
       choose.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
       choose.showSaveDialog(label1);
       choose.setAcceptAllFileFilterUsed(false);
       File d2 = choose.getCurrentDirectory();
        try {        
            copytoDirectory(d2);
        } catch (IOException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }                              

    private void copytoDirectory(File d2) throws IOException {
       File d1 = new File ("C:\\MEIA");
        File  newD2= new File (d2.getAbsolutePath()+"\\MEIA_Backup");
        newD2.mkdirs();
        Path destPath = newD2.toPath();
        for (File sourceFiles :d1.listFiles()) {
            Path sourcePath = sourceFiles.toPath();
            Files.copy(sourcePath, destPath.resolve(sourcePath.getFileName()));
        }
        write(username,"C:\\MEIA\\bitacora_backup.txt",newD2.getAbsolutePath());          
    }//GEN-LAST:event_RespaldoActionPerformed
    private void write(String user, String path, String file) throws IOException {
        File bitacora = new File (path);
        String date = LocalDateTime.now().toString();
        FileWriter w = new FileWriter(bitacora,true);        
        w.write(file+"|"+ user+"|"+date+"\r\n");
        w.close();
        writeDesc();
    }
    private void writeDesc() throws IOException {
       String date = LocalDateTime.now().toString();
        File descBitacora = new File ("C:\\MEIA\\desc_bitacora_backup.txt");
        if(descBitacora!=null) {     
        BufferedReader reader = new BufferedReader(new FileReader(descBitacora));
        String line  = reader.readLine();
        String [] separatedLine = line.split(Pattern.quote("|"));
        int registros = Integer.valueOf(separatedLine[5]);  
        registros ++;   
        
        String nc = "\r\n"+separatedLine[0]+"|"+username+separatedLine[1]+"|"+separatedLine[2]+"|"+date+"|"+username +"|"+String.valueOf(registros);
        FileWriter writer = new FileWriter(descBitacora,false);        
        writer.write(nc);
        reader.close();
        writer.close();      
        }else{
            
            String toWrite = "Descriptor Bitacora|"+date+"|"+username+"|"+date+"|"+username+"|1";
            FileWriter writer = new FileWriter(descBitacora, true);
            writer.write(toWrite);
            writer.close();
            
        }
    }
    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        //Agregar Uusuarios
        this.setVisible(false);
        new Registrate(true, username).setVisible(true); 
    }//GEN-LAST:event_AgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin(username).setVisible(true);
            }
        });
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Agregar;
    private javax.swing.JMenuItem Busqueda;
    private javax.swing.JMenuItem Respaldo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private java.awt.Label label1;
    private java.awt.Label usuario;
    // End of variables declaration//GEN-END:variables

    
}
