/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author lam_m
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
         try{
            File f = new File("C:\\MEIA");
            File u = new File("C:\\MEIA\\usuario.txt");
            File a = new File("C:\\MEIA\\desc_usuario.txt");
            File b = new File("C:\\MEIA\\Master.txt");
            File c = new File("C:\\MEIA\\desc_Master.txt");
            File ba = new File("C:\\MEIA\\bitacora_backup.txt");
            File bac = new File("C:\\MEIA\\desc_bitacora_backup.txt");
            File l = new File("C:\\MEIA\\lista.txt");
            File dl = new File("C:\\MEIA\\desc_lista.txt");
            File Ml = new File("C:\\MEIA\\Master_lista.txt");
            File lu = new File("C:\\MEIA\\Lista_usuario.txt");
            File dlu = new File("C:\\MEIA\\Desc_Lista_usuario.txt");
            File ilu = new File("C:\\MEIA\\Indice_ListaUsuario.txt");
            File dilu = new File("C:\\MEIA\\Desc_Indice_ListaUsuario.txt");
            File co = new File("C:\\MEIA\\Correo.txt");
            
            if(!f.exists()){
                f.mkdir();
            }
            if(!co.exists()){
                BufferedWriter bw = new BufferedWriter(new FileWriter(co));
                bw.close();
            }
            if(!ilu.exists()){
                BufferedWriter bw = new BufferedWriter(new FileWriter(ilu));
                bw.close();
            }
            if(!dilu.exists()){
                BufferedWriter bw = new BufferedWriter(new FileWriter(dilu));
                bw.close();
            }
            if(!u.exists()){
                BufferedWriter bw = new BufferedWriter(new FileWriter(u));
                bw.close();
            }
            if(!lu.exists()){
               BufferedWriter bw = new BufferedWriter(new FileWriter(lu));
               bw.close();
            }
             if(!dlu.exists()){
               BufferedWriter bw = new BufferedWriter(new FileWriter(dlu));
               bw.close();
            }
            
            if(!Ml.exists()){
                BufferedWriter bw = new BufferedWriter(new FileWriter(Ml));
                bw.close();
            }
            if(!l.exists()){
                BufferedWriter bw = new BufferedWriter(new FileWriter(l));
                bw.close();
            }
            if(!dl.exists()){
                BufferedWriter bw = new BufferedWriter(new FileWriter(dl));
                bw.close();
            }
            if(!a.exists()){
                BufferedWriter bw = new BufferedWriter(new FileWriter(a));
                bw.close();
            }
            if(!b.exists()){
                BufferedWriter bw = new BufferedWriter(new FileWriter(b));
                bw.close();
            }
            if(!c.exists()){
                BufferedWriter bw = new BufferedWriter(new FileWriter(c));
                bw.close();
            }
            
            if(!ba.exists()){
                BufferedWriter bw = new BufferedWriter(new FileWriter(ba));
                bw.close();
            }
            if(!bac.exists()){
                BufferedWriter bw = new BufferedWriter(new FileWriter(bac));
                bw.close();
            }
        }catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        Usuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        LoginBtn = new java.awt.Button();
        button2 = new java.awt.Button();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MEIA");
        setMaximumSize(new java.awt.Dimension(500, 400));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(Usuario);
        Usuario.setBounds(49, 62, 217, 22);

        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(49, 39, 43, 16);

        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(49, 91, 65, 16);
        getContentPane().add(Password);
        Password.setBounds(49, 117, 217, 22);

        LoginBtn.setActionCommand("Login");
        LoginBtn.setLabel("Login");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LoginBtn);
        LoginBtn.setBounds(260, 280, 47, 24);

        button2.setLabel("Registrarse");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2);
        button2.setBounds(159, 279, 81, 24);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/LOGO_MEIA2 (2).png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-4, 3, 510, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        Registrate r = new Registrate(false, "");
        this.setVisible(false);
        r.setVisible(true);
    }//GEN-LAST:event_button2ActionPerformed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // LOGIN
        try{
            File u = new File("C:\\MEIA\\usuario.txt");
            String linea = "";
            Boolean buscarA = true;
            FileReader frp = new FileReader(u);
            BufferedReader brp = new BufferedReader(frp);
            while((linea=brp.readLine())!= null){
                String username = linea.substring(0,linea.indexOf("|"));
                String intento = Usuario.getText();
                if(username.equals(intento)){

                   String nombre = linea.substring(linea.indexOf("|")+1,linea.length());
                   String apellido = nombre.substring(nombre.indexOf("|")+1,nombre.length());
                   String password = apellido.substring(apellido.indexOf("|")+1,apellido.length());
                   String rol = password.substring(password.indexOf("|")+1,password.length());
                   String status = rol.substring(rol.length()-1);

                   password = password.substring(0,password.indexOf("|"));
                   rol = rol.substring(0,rol.indexOf("|"));
                   String pa = getMD5(Arrays.toString(Password.getPassword()));
                   if(pa.equals(password) && status.equals("1")){//Tambien que no este de baja
                       buscarA = false;
                       this.setVisible(false);
                       if(rol.equals("1")){//Se trata del admin
                           new Admin(username).setVisible(true);
                           break;
                       }else{//Se trata de un usuario normal
                           new Usuario(username).setVisible(true);
                           break;
                       }
                   }else{
                       buscarA = false;
                       if(status.equals("1")){
                            JOptionPane.showMessageDialog(rootPane, "Contraseña incorrecta", "Error Message", JOptionPane.ERROR_MESSAGE);
                            break;
                       }else{
                            JOptionPane.showMessageDialog(rootPane, "Usuario de baja", "Error Message", JOptionPane.ERROR_MESSAGE);
                            break;
                       }
                   }
                }
            }
            if(buscarA){
                u = new File("C:\\MEIA\\Master.txt");
                linea = "";
                
                frp = new FileReader(u);
                brp = new BufferedReader(frp);
                while((linea=brp.readLine())!= null){
                    String username = linea.substring(0,linea.indexOf("|"));
                    String intento = Usuario.getText();
                    if(username.equals(intento)){
                       String nombre = linea.substring(linea.indexOf("|")+1,linea.length());
                       String apellido = nombre.substring(nombre.indexOf("|")+1,nombre.length());
                       String password = apellido.substring(apellido.indexOf("|")+1,apellido.length());
                       String rol = password.substring(password.indexOf("|")+1,password.length());
                       String status = rol.substring(rol.length()-1);
                       password = password.substring(0,password.indexOf("|"));
                       rol = rol.substring(0,rol.indexOf("|"));
                       
                       String pa = getMD5(Arrays.toString(Password.getPassword()));
                       
                       if(pa.equals(password) && status.equals("1")){//Tambien que no este de baja
                           this.setVisible(false);
                           if(rol.equals("1")){//Se trata del admin
                               new Admin(username).setVisible(true);
                               break;
                           }else{//Se trata de un usuario normal
                               new Usuario(username).setVisible(true);
                               break;
                           }
                       }else{
                           if(status.equals("1")){
                                JOptionPane.showMessageDialog(rootPane, "Contraseña incorrecta", "Error Message", JOptionPane.ERROR_MESSAGE);
                                break;
                           }else{
                                JOptionPane.showMessageDialog(rootPane, "Usuario de baja", "Error Message", JOptionPane.ERROR_MESSAGE);
                                break;
                           }
                       }
                    }
                }
            }   
        }catch(HeadlessException | IOException e){
            
            }
        
        
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    public static String getMD5(String input) {
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] messageDigest = md.digest(input.getBytes());
            BigInteger number = new BigInteger(1, messageDigest);
            String hashtext = number.toString(16);

            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext;
            }
            return hashtext;
        }
        catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button LoginBtn;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Usuario;
    private java.awt.Button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JOptionPane jOptionPane1;
    // End of variables declaration//GEN-END:variables
}
